apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod
  namespace: default
spec:
  serviceAccountName: nginx-serviceaccount
  containers:
  - name: s3-test
    image: amazonlinux:2
    command: ["/bin/sh", "-c"]
    args:
      - yum install -y aws-cli && \
        echo "Listing S3 Buckets..." && \
        aws s3 ls && \
        sleep 3600
